# Generated by Django 2.1.1 on 2018-11-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('distance', models.CharField(max_length=30)),
                ('date_posted', models.DateTimeField(verbose_name='Posted Date')),
            ],
        ),
    ]
