# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT sensors.wsgi

beta_settings:
    cloud_sql_instances: sensors-223804:us-west1:sensors-instance1

runtime_config:
  python_version: 3
# [END runtime]
